/* This file is generated. Edit at your own risk. */
#define ALTHTTPD_VERSION_NUMBER "0.9"
#define ALTHTTPD_VERSION_HASH "[ef1ffc360725]"
#define ALTHTTPD_VERSION_TIME "2022-01-15T15:21:02.722"
#define ALTHTTPD_VERSION ALTHTTPD_VERSION_HASH " " ALTHTTPD_VERSION_TIME
